[package]
name = "day_17"
version = "0.1.0"
authors = ["pingzing <mcalistern@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
itertools = "0.9.0"